language: rust

env:
  global:
    - PROJECT_NAME=cute-log

matrix:
  include:
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
      cache: cargo
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      cache: cargo

sudo: false

script:
    - cargo build --no-default-features
    - cargo build --no-default-features --features timestamp
    - cargo build --no-default-features --features color
    - cargo test
